[package]
name = "ota"
version = "0.1.0"
authors = ["Mike Yagley <myagley@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
futures = "0.1"
log = "0.4"
tokio = "0.1"
tokio-signal = "0.2"

azure-iot-mqtt = { path = "../azure-iot-mqtt" }
